package com.antigravity.smarthub.core.model

/**
 * Normalized Thermal Status from PowerManager HAL 2.0 & Battery sensors.
 */
enum class ThermalStatusLevel {
    NOMINAL,      // Safe operation (< 39°C)
    WARM,         // Elevated (39°C - 42°C)
    MODERATE,     // Moderate throttling starting (43°C - 46°C)
    SEVERE,       // Severe thermal throttling (47°C - 49°C)
    CRITICAL      // Emergency shutdown / protection active (>= 50°C)
}

/**
 * Capability Tier active on device.
 */
enum class PrivilegeTier {
    TIER_0_STOCK,      // Official APIs only
    TIER_1_SHIZUKU,    // Shizuku / WRITE_SECURE_SETTINGS shell access
    TIER_2_ROOT        // Kernel / sysfs direct access
}

/**
 * High-Level Operating Profiles determined by ProfileResolver.
 */
enum class SmartHubProfile(val priority: Int, val displayName: String) {
    P0_THERMAL_EMERGENCY(0, "Thermal Emergency Override"),
    P1_CRITICAL_BATTERY(1, "Critical Battery Saver"),
    P2_CHARGING_THERMAL_GUARD(2, "Charging Thermal Guard"),
    P3_GAMING_HIGH_LOAD(3, "Gaming & Sustained Performance"),
    P4_MEDIA_READING(4, "Media & Screen Energy Saver"),
    P5_DAILY_ADAPTIVE(5, "Daily Adaptive Balanced"),
    P6_OVERNIGHT_DEEP_IDLE(6, "Overnight Deep Idle")
}

/**
 * Real-time aggregated Device Telemetry State.
 */
data class DeviceState(
    val batteryPercent: Int = 100,
    val isCharging: Boolean = false,
    val batteryTempC: Float = 30.0f,
    val apTempC: Float = 35.0f,
    val thermalStatus: ThermalStatusLevel = ThermalStatusLevel.NOMINAL,
    val memoryAvailableMb: Long = 3000,
    val memoryPsiAvg10: Float = 0.0f,
    val isScreenOn: Boolean = true,
    val foregroundPackage: String = "",
    val activeRefreshRateMode: Int = 0, // 0 = 120Hz, 1 = 60Hz on Samsung One UI
    val privilegeTier: PrivilegeTier = PrivilegeTier.TIER_0_STOCK
)

/**
 * Base sealed interface for typed system actions.
 */
sealed interface SystemAction {
    val actionId: String
    val requiredTier: PrivilegeTier
    val description: String

    data class SetRefreshRate(
        val targetMode: Int // 0=Adaptive 120Hz, 1=Standard 60Hz
    ) : SystemAction {
        override val actionId: String = "CMD_SET_REFRESH_RATE_$targetMode"
        override val requiredTier: PrivilegeTier = PrivilegeTier.TIER_1_SHIZUKU
        override val description: String = "Set Samsung refresh_rate_mode to $targetMode"
    }

    data class SetStandbyBucket(
        val packageName: String,
        val targetBucket: String // active, working_set, frequent, rare, restricted
    ) : SystemAction {
        override val actionId: String = "CMD_SET_STANDBY_BUCKET_${packageName}_$targetBucket"
        override val requiredTier: PrivilegeTier = PrivilegeTier.TIER_1_SHIZUKU
        override val description: String = "Set app standby bucket for $packageName to $targetBucket"
    }

    data class SetAppOpsBackground(
        val packageName: String,
        val allow: Boolean
    ) : SystemAction {
        override val actionId: String = "CMD_SET_APPOPS_BG_${packageName}_$allow"
        override val requiredTier: PrivilegeTier = PrivilegeTier.TIER_1_SHIZUKU
        override val description: String = "Set RUN_ANY_IN_BACKGROUND for $packageName to $allow"
    }
}

/**
 * Safety Veto Result generated by Safety Governor.
 */
data class SafetyVetoResult(
    val isAllowed: Boolean,
    val vetoReason: String = ""
)
