package com.antigravity.smarthub.core.model

import com.antigravity.smarthub.core.telemetry.TelemetryState
import com.antigravity.smarthub.core.telemetry.TelemetryValue

/**
 * Normalized Thermal Status from PowerManager HAL 2.0 & Battery sensors.
 */
enum class ThermalStatusLevel {
    NOMINAL,      // Safe operation (< 39°C)
    WARM,         // Elevated (39°C - 42°C)
    MODERATE,     // Moderate throttling starting (43°C - 46°C)
    SEVERE,       // Severe thermal throttling (47°C - 49°C)
    CRITICAL      // Emergency shutdown / protection active (>= 50°C)
}

/**
 * Capability Tier active on device.
 */
enum class PrivilegeTier {
    TIER_0_STOCK,      // Official APIs only
    TIER_1_SHIZUKU,    // Shizuku / WRITE_SECURE_SETTINGS shell access
    TIER_2_ROOT        // Kernel / sysfs direct access
}

/**
 * Single Canonical Profile Authority determined by StateMachineEngine.
 */
enum class SmartHubProfile(val priority: Int, val displayName: String) {
    P0_THERMAL_EMERGENCY(0, "Thermal Emergency Override"),
    P1_CRITICAL_BATTERY(1, "Critical Battery Saver"),
    P2_CHARGING_THERMAL_GUARD(2, "Charging Thermal Guard"),
    P3_GAMING_HIGH_LOAD(3, "Gaming & Sustained Performance"),
    P4_MEDIA_READING(4, "Media & Screen Energy Saver"),
    P5_DAILY_ADAPTIVE(5, "Daily Adaptive Balanced"),
    P6_OVERNIGHT_DEEP_IDLE(6, "Overnight Deep Idle")
}

/**
 * Hardware capability result after executing/verifying action.
 */
enum class CapabilityResult {
    SUPPORTED,
    PARTIALLY_SUPPORTED,
    IGNORED_BY_OEM,
    UNAVAILABLE
}

/**
 * Real-time quality-aware Device Telemetry State.
 * Every safety-relevant metric retains explicit TelemetryValue<T> state.
 */
data class DeviceState(
    val batteryPercent: TelemetryValue<Int> = TelemetryValue.unavailable(),
    val isCharging: TelemetryValue<Boolean> = TelemetryValue.unavailable(),
    val batteryTempC: TelemetryValue<Float> = TelemetryValue.unavailable(),
    val apTempC: TelemetryValue<Float> = TelemetryValue.unavailable(),
    val thermalStatus: TelemetryValue<ThermalStatusLevel> = TelemetryValue.unavailable(),
    val thermalHeadroom: TelemetryValue<Float> = TelemetryValue.unavailable(),
    val thermalForecastHeadroom: TelemetryValue<Float> = TelemetryValue.unavailable(),
    val memoryAvailableMb: TelemetryValue<Long> = TelemetryValue.unavailable(),
    val memoryPsiAvg10: TelemetryValue<Float> = TelemetryValue.unavailable(),
    val isScreenOn: TelemetryValue<Boolean> = TelemetryValue.unavailable(),
    val foregroundPackage: TelemetryValue<String> = TelemetryValue.unavailable(),
    val activeRefreshRateMode: TelemetryValue<Int> = TelemetryValue.unavailable(),
    val effectiveRefreshRateHz: TelemetryValue<Float> = TelemetryValue.unavailable(),
    val displayState: TelemetryValue<String> = TelemetryValue.unavailable(),
    val privilegeTier: PrivilegeTier = PrivilegeTier.TIER_0_STOCK
)

/**
 * Base sealed interface for typed system actions.
 */
sealed interface SystemAction {
    val actionId: String
    val requiredTier: PrivilegeTier
    val description: String

    data class SetRefreshRate(
        val targetMode: Int // 0=Adaptive 120Hz, 1=Standard 60Hz
    ) : SystemAction {
        override val actionId: String = "CMD_SET_REFRESH_RATE_$targetMode"
        override val requiredTier: PrivilegeTier = PrivilegeTier.TIER_1_SHIZUKU
        override val description: String = "Set Samsung refresh_rate_mode to $targetMode"
    }

    data class SetStandbyBucket(
        val packageName: String,
        val targetBucket: String // active, working_set, frequent, rare, restricted
    ) : SystemAction {
        override val actionId: String = "CMD_SET_STANDBY_BUCKET_${packageName}_$targetBucket"
        override val requiredTier: PrivilegeTier = PrivilegeTier.TIER_1_SHIZUKU
        override val description: String = "Set app standby bucket for $packageName to $targetBucket"
    }

    data class SetAppOpsBackground(
        val packageName: String,
        val allow: Boolean
    ) : SystemAction {
        override val actionId: String = "CMD_SET_APPOPS_BG_${packageName}_$allow"
        override val requiredTier: PrivilegeTier = PrivilegeTier.TIER_1_SHIZUKU
        override val description: String = "Set RUN_ANY_IN_BACKGROUND for $packageName to $allow"
    }
}

/**
 * Safety Veto Result generated by Safety Governor.
 */
data class SafetyVetoResult(
    val isAllowed: Boolean,
    val vetoReason: String = ""
)

/**
 * Explainable Action History Record for UI inspection & audit trail.
 */
data class ActionHistoryRecord(
    val timestampMs: Long = System.currentTimeMillis(),
    val previousProfile: SmartHubProfile,
    val newProfile: SmartHubProfile,
    val triggeringTelemetrySummary: String,
    val actionId: String,
    val actionDescription: String,
    val safetyVetoResult: SafetyVetoResult,
    val capabilityResult: CapabilityResult,
    val previousValue: String?,
    val requestedValue: String?,
    val verifiedValue: String?,
    val rolledBack: Boolean = false,
    val restored: Boolean = false
)
